apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.68.61
      user: root
      port: 22
      keyPath: ~/.ssh/raspberry
    role: controller+worker
  - ssh:
      address: 192.168.68.60
      user: root
      port: 22
      keyPath: ~/.ssh/raspberry
    role: worker
